name: Build Application

on:
  workflow_call:

jobs:
  latest_release:
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.get_latest_release.outputs.tag_name }}
    steps:
      - name: Get Latest Release
        id: get_latest_release
        uses: joutvhu/get-release@v1
        with:
          owner: PrismLauncher
          repo: PrismLauncher
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    needs: latest_release
    with:
      build_type: Release
      is_qt_cached: false
      ref: ${{ needs.latest_release.outputs.tag }}

  